//
//  AWSGoogleSignInProvider.h
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
#import <Foundation/Foundation.h>
#import "AWSSignInProvider.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * `AWSGoogleSignInProvider` adopts the `AWSSignInProvider` protocol.
 *
 * It works with the Google Sign In SDK internally and requires the Google Client ID provided by Google.
 */
@interface AWSGoogleSignInProvider : NSObject <AWSSignInProvider>

/**
 Fetches the shared instance for AWSGoogleSignInProvider.
 
 @return the single instance of AWSGoogleSignInProvider
 */
+ (instancetype)sharedInstance;

@end

NS_ASSUME_NONNULL_END
